### ISSUE TITLE
Maintainer Issues for RC

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#245]
## Bugs to fix
* ~~Missing: HierarchyComposition - SetPathGenerator #190~~ fixed in Beta3
* ~~Exception for no topology selected is cryptic #195~~
* [x] RequiresDuplicateDetection combined with SLR will lead to a message loss #201 @SeanFeldman PR #240
* [x] Validate default values #241 @seanfeldman PR #243
    * [x] IValidationStrategy should return validation result, not just a bool #230 @seanfeldman PR #247
    * [x] Exception for sanitization is confusing #228 @seanfeldman PR #247
* Validation 
* [x] Missing: DiscriminatorBasedIndividualization SetDiscriminatorGenerator #188 @seanfeldman PR #250
* [x] Ensure compatibility with SC #217 => issue #235 @melkio PR #251
* [x] Batched operation estimate should be working with variable message size #176 @seanfeldman
* [x] Validation and sanitization API friction #252 @seanfeldman SPIKE PRs ~~#255 #257 #260~~ #265 
* Connections strings & namespaces
   * [x] Securing Connection Strings To Namespaces #229 @yvesgoeleven PR #249
   * [x] Disable Requires connection string #163 @yvesgoeleven PR #249
* [x] Remove transaction settings #192 @seanfeldman
* [x] Improve exception message: No publishers configured for `X` #180 @melkio PR #262
* [x] Follow standard component naming #204 
   * [x] Adjust namespaces #263 @melkio 
   *  ~~New nuget package name #264~~ (out of RC for next major)

### Quality ensurance
* [x] Validate that we support an ASB namespace hierarchy #6 @yvesgoeleven
* [x] Long running tests (Detect memory leaks, ensure that we can handle any ASB throws at us without going down)
* [x] Upgrade compatibility testing
* ~~Verify still working with SC~~ replaced by https://github.com/Particular/PlatformDevelopment/issues/856
* _Figure out if specific performance tests are needed (`ForwardingTopology` is tested, but not `EndpointOrientedTopology`)_ Taking this off as we didn't focus on this right now.

### Upcoming changes transport seam
* [x] Error pipeline

### RC-completed (depends on Core RC)
* [x] Ensure PerfTests are on the RC version (latest & greatest) (currently beta5)
* [x] Publish RC packages on nuget

**Comment by SeanFeldman** [comment]
Documentation needs to be validated against some of these changes

**Comment by melkio** [comment]
Updated description splitting #204 into #263 (I'm working on it) and #264 (out of RC scope)

**Comment by SeanFeldman** [comment]
Closing this as we're done with RC and working towards RTM.
