### ISSUE TITLE
V7 RTM

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#334]
## Items to complete

- ~~Change package author name -> use updated NugetPackager https://github.com/Particular/V6Launch/issues/4~~ not needed
- ~~[Performance issues with ConnectionString..ctor(String)](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/332)~~ not critical, can wait
- [x] [Delivery count to respect Immediate retries and user settings](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/308)
- [x] [Disable prefetching by default with transport transaction None](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/340)
- [x] [MessageReceiverNotifier should not invoke recoverability when receiving](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/349)
- [x] [Outbox doesn't work with ASB transport](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/352)
- [x] Create release notes (general ones, similar to the [Core ones with milestones](https://github.com/Particular/V6Launch/issues/75#issuecomment-251098093))
- [x] Update [V6Launch status list](https://github.com/Particular/V6Launch/issues/4)

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers anything missing here?

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers is there anything that would prevent us from marking ASB as RTM ready?

**Comment by yvesgoeleven** [comment]
@SeanFeldman I don't think anything is preventing us to go live

**Comment by SeanFeldman** [comment]
well, except [Outbox](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/352) 😺
