### ISSUE TITLE
Update to NServiceBus v6

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#90]
Task force: @SeanFeldman @yvesgoeleven @melkio 

This is the Azure ServiceBus adapter epic which incorporates the work for making the transport work with Core v6.

#### Things left todo:

- [x] Maximum batch size for brokered messages is not calculated properly #86 @SeanFeldman PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/108 
- [x] Implement StartupCheckResult https://github.com/Particular/NServiceBus.AzureServiceBus/issues/96 @melkio PR #113 
- [x] Implement improved transport seam #95 @yvesgoeleven PR #116 ==> depends on `Core` https://github.com/Particular/NServiceBus/pull/3308
-  ~~Native deadlettering https://github.com/Particular/NServiceBus.AzureServiceBus/issues/82 ==> depends on `Core` https://github.com/Particular/NServiceBus/issues/3354~~
- [x] Finish Forwarding Topology #13 @seanfeldman PR #118 
    - [x] Remove ForwardTo on all entities #117 @seanfeldman PR #128
   - [x] Polymorphic events (in context of ForwardingTopology) #53 @seanfeldman PR #122 
- [x] Map namespace name to connectionstring https://github.com/Particular/NServiceBus.AzureServiceBus/issues/93 @melkio PR #125 
-  ~~Integrate Error Queue https://github.com/Particular/NServiceBus.AzureServiceBus/issues/99 @seanfeldman ==> depends on `PlatformDev` https://github.com/Particular/PlatformDevelopment/issues/632~~
- [x] Implement passive namespace fallback https://github.com/Particular/NServiceBus.AzureServiceBus/issues/103 @yvesgoeleven #129 
- [x] Configure publisher names #115 @melkio PR #152 
- [x] Support for callbacks https://github.com/Particular/NServiceBus.AzureServiceBus/issues/80 @SeanFeldman ==> depends on `Core` ~~https://github.com/Particular/NServiceBus/issues/3369~~ ~~https://github.com/Particular/NServiceBus/issues/3406~~ ==> https://github.com/Particular/NServiceBus/issues/3652 ==> proceeding with it as-is to confirm it works
- [x] Support scaleout in different instance modes #124 @yvesgoeleven ==> depends on `Core` ~~https://github.com/Particular/NServiceBus/issues/3495~~ ==> [POC](https://github.com/Particular/NServiceBus/issues/3638) to prove it will work

#### Things to clean up

- [x] Remove 'old code'
- [x] Review & simplify code only configuration API #92 @seanfeldman
   - [x] Forwarding topology and `EnablePartitioning` setting #131 @seanfeldman PR #133 
   - [x] `ConnectivityMode` is missing #130 @seanfeldman PR #136 
   - [x] `MaxDeliveryCount` #137 @seanfeldman PR #138 
- ~~Implement different strategy for resolving specific endpoint namespaces https://github.com/Particular/NServiceBus.AzureServiceBus/issues/4~~
- [x] Completion Callback Tx Scope Review #78
- [x] Determine correct TransportTransactionMode based on number of namespaces #97 @seanfeldman PR #141
- [x] Match `RequiredConsistency` with settings from the core #101 
- [x] Move ReadOnlySettingsExtensions to the core  https://github.com/Particular/NServiceBus.AzureServiceBus/issues/98
- [x] Throw when PurgeOnStartup is requested #100 @melkio PR #109
- ~~Get publisher name injected into the standard topology for subscribe & unsubscribe #105~~
- [x] `RepeatedFailuresOverTimeCircuitBreaker` should state what message pump is failing to receive messages #126 @seanfeldman PR #140 
- ~~Add Host Info When Sending to DLQ #142 ==> depends on `Core`~~ => release as minor after v6 launch assuming the core endpoint instance id decission makes it into v6
- ~~Add Host Info When Sending to DLQ #143 ==> depends on `Core`~~ => release as minor after v6 launch assuming the core endpoint instance id decission makes it into v6

#### Things to validate & document

-  **All** Documentation: https://github.com/Particular/docs.particular.net/issues/1255
- [x] Validate consistent usage of ConfigureAwait(false) #94 @melkio PR #111 
- [x] Trace messages that are larger then the maximum message size allowed by Azure ServiceBus #57
- [x] Validate that NoTransaction is the correct value for TransportTransaction parameter in pushcontext #102 @yvesgoeleven 
- [x] Validate CriticalError behavior #104 @yvesgoeleven @seanfeldman
- [x] Validate SendVia feature #83 @seanfeldman
- [x] Validate Message lock renewal #19 @seanfeldman PR #153 
- [x] Validate that custom headers promote to BrokeredMessage properties (and vice versa) #7 @yvesgoeleven
- ~~Test EndpointOriented (standard) topology with a long running process~~ #76 ==> moved to https://github.com/Particular/EndToEnd/issues/2
- ~~Test Forwarding topology with a long running process~~ #106 ==> moved to https://github.com/Particular/EndToEnd/issues/2
- [x] Create Compatibility tests similar to other transports #120 @seanfeldman
- [x] validate that we support an ASB namespace hierarchy #6

**Comment by andreasohlund** [comment]
What's the current state of this taskforce? Any blockers?

**Comment by andreasohlund** [comment]
Who's the taskforce lead?

**Comment by SeanFeldman** [comment]
@andreasohlund taskforce is working on the [v6 launch](https://github.com/Particular/NServiceBus.AzureServiceBus/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project%3A+V6+Launch%22) associated items. 

Two items were blocked and are worked on right now:

1. https://github.com/Particular/NServiceBus.AzureServiceBus/issues/80 (@seanfeldman) => connecting with other transports to figure out what needs to be done
1. https://github.com/Particular/NServiceBus.AzureServiceBus/issues/124 (@yvesgoeleven) => POC

@yvesgoeleven and myself co-lead this.

**Comment by SeanFeldman** [comment]
Covered by [releasing ASB beta](https://github.com/Particular/PlatformDevelopment/issues/718)
