### ISSUE TITLE
Code only configuration API

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#92]
To be consistent with core v6 & the rest of the transports & persistences, we should switch to a code only configuration model on top of SettingsHolder.

Todo: should we provide an overlay for backward compat of xml based config model as well?

TODO
- [x] The new configuration API needs simplification
  - [x] `EnablePartitioning` for topics on `ForwardingTopology` #131 
  - [x] `ConnectivityMode` is missing #130 
  - [x] `MaxDeliveryCount` #137
  - [x] `PrefetchCount` on both `MessaginFactory` and `MessageReceiver` #151

**Comment by yvesgoeleven** [comment]
https://github.com/Particular/NServiceBus.AzureServiceBus/issues/20

**Comment by yvesgoeleven** [comment]
The new configuration API needs simplification & doco

**Comment by SeanFeldman** [comment]
For XML based configuration, we could provide a sample to show how to do it. 
Same is applicable for Cloud Services configuration (.cscfg)

**Comment by SeanFeldman** [comment]
1. `ConnectivityMode` - not implemented
1. `ServerWaitTime` - not implemeted
1. `BackoffTimeInSeconds` - this used to be on the receiving poll. We're now using msgReceiver.OnMessage, so think it's not needed (do you know?)
1. `BatchSize` -- not sure where's this one in the v7
1. `EnablePartitioning` won't work with ForwardingTopo :disappointed:
1. `SupportOrdering` -- i question the value of this one

@yvesgoeleven can you comment of these?

**Comment by yvesgoeleven** [comment]
1. Definitly needed, we need to add this back
2. Not needed anymore
3. Not needed anymore
4. Uses PrefetchCount setting now, so not needed anymore
5. Add topology specific startup check?
6. Why? It's easier to reason about queue content if it doesn't change order...

**Comment by SeanFeldman** [comment]
> It's easier to reason about queue content if it doesn't change order...

It's defined for both queues and topics. We say "order is not promised" and at the same time we're exposing this bare-metal configuration. Confusing, isn't it?

**Comment by yvesgoeleven** [comment]
Hmm, it is, remove it then...

**Comment by SeanFeldman** [comment]
We had a default set to `true` in v6 and before. In v7 we're breaking this by changing the default to _false_. Those that rely on the setting to be `true` need a simple way to configure it. If we remove configuration specific to `SupportOrdering`, using full blown description factory is all that is left. Therefore I'm going to leave it to reduce friction for those that need to go back to `SupportOrdering=true`.

**Comment by SeanFeldman** [comment]
[`AzureServiceBusBatchingSettings`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/c5cac1ee4a627c667d950ec043dcda020ba12681/src/Transport/Config/ExtensionMethods/AzureServiceBusTransportExtensions.cs#L32) is never used. I suggest we axe it since we've got [`MessageSizePaddingPercentage`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/c5cac1ee4a627c667d950ec043dcda020ba12681/src/Transport/Config/ExtensionPoints/AzureServiceBusMessageSenderSettings.cs#L50) for batching needs.

**Comment by SeanFeldman** [comment]
@yvesgoeleven we don't set [`PrefetchCount` for message receivers](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/c4fdfda11371bea122838bcf431f346126241dd0/src/Transport/Config/ExtensionPoints/AzureServiceBusMessageReceiverSettings.cs#L36). Should we?

**Comment by SeanFeldman** [comment]
@yvesgoeleven I don't really like the suggested name for the standard topology (`EndpointOrientedTopology`). On a fence if we should rename it or not.

**Comment by mikeminutillo** [comment]
Is the plan of attack up to date for this issue?

> `MaxDeliveryCount` change from 6 to 10

appears to be done [here](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/138)

> `ForwardingTopology` startup task will not allow partitioning on topic #131

is done

Is doco the only set of tasks left to do for this issue? Are all the doco tasks blocked waiting for the [restructure](https://github.com/Particular/docs.particular.net/issues/1270)? What needs to happen to close this issue?

**Comment by yvesgoeleven** [comment]
@mikeminutillo we're still simplifying it, see the top todo that isn't marked as finished. Doco is indeed moved over to the doco repo, so we can close this issue once we're happy with the simplification

**Comment by SeanFeldman** [comment]
Finished and 4 bugs fixed as a result of this work.
Configuration will be completed once #152 is merged.
